name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_EMAILJS_SERVICE_ID: ${{ secrets.EMAILJS_SERVICE_ID }}
      NEXT_PUBLIC_EMAILJS_TEMPLATE_ID: ${{ secrets.EMAILJS_TEMPLATE_ID }}
      NEXT_PUBLIC_EMAILJS_PUBLIC_KEY: ${{ secrets.EMAILJS_PUBLIC_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: echo "Checking environment variables"
      - run: echo $NEXT_PUBLIC_EMAILJS_SERVICE_ID && echo $NEXT_PUBLIC_EMAILJS_TEMPLATE_ID && echo $NEXT_PUBLIC_EMAILJS_PUBLIC_KEY
      - run: npm run lint
      - run: npm test
      - run: npm run build
