name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  EMAILJS_SERVICE_ID: ${{ secrets.EMAILJS_SERVICE_ID }}
  EMAILJS_TEMPLATE_ID: ${{ secrets.EMAILJS_TEMPLATE_ID }}
  EMAILJS_USER_ID: ${{ secrets.EMAILJS_USER_ID }}

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    outputs:
      allow_missing: ${{ steps.set-env.outputs.allow_missing }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci --prefer-offline --no-audit --progress=false
      - name: Display EmailJS secret status
        run: |
          echo "EMAILJS_SERVICE_ID: ${EMAILJS_SERVICE_ID:-Not Set}"
          echo "EMAILJS_TEMPLATE_ID: ${EMAILJS_TEMPLATE_ID:-Not Set}"
          echo "EMAILJS_USER_ID: ${EMAILJS_USER_ID:-Not Set}"
      - name: Skip secret check if variables are missing
        id: set-env
        run: |
          missing=false
          [ -z "$EMAILJS_SERVICE_ID" ] && missing=true
          [ -z "$EMAILJS_TEMPLATE_ID" ] && missing=true
          [ -z "$EMAILJS_USER_ID" ] && missing=true
          if [ "$missing" = true ]; then
            echo "ALLOW_MISSING_EMAILJS_SECRETS=true" >> "$GITHUB_ENV"
            echo "allow_missing=true" >> "$GITHUB_OUTPUT"
          else
            echo "allow_missing=false" >> "$GITHUB_OUTPUT"
          fi
      - run: npm run check:secrets

  build:
    needs: check-secrets
    runs-on: ubuntu-latest
    env:
      ALLOW_MISSING_EMAILJS_SECRETS: ${{ needs.check-secrets.outputs.allow_missing }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
codex/emailjs-환경-변수-및-ci-개선
      - run: npm ci
      - run: echo "Checking environment variables"
      - run: echo $EMAILJS_SERVICE_ID && echo $EMAILJS_TEMPLATE_ID && echo $EMAILJS_USER_ID
      - name: Validate Environment Variables
        run: |
          if [ -z "$EMAILJS_SERVICE_ID" ] || [ -z "$EMAILJS_TEMPLATE_ID" ] || [ -z "$EMAILJS_USER_ID" ]; then
            echo "Missing one or more EmailJS environment variables.";
            exit 1;
          fi

      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci || npm ci
 main
      - run: npm run lint
      - run: npm test
      - run: npm run build
