name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # EmailJS credentials should be configured as GitHub Secrets.
      # CI will fail if these values remain as the fallback 'placeholder'.
      EMAILJS_SERVICE_ID: ${{ secrets.EMAILJS_SERVICE_ID || 'placeholder' }}
      EMAILJS_TEMPLATE_ID: ${{ secrets.EMAILJS_TEMPLATE_ID || 'placeholder' }}
      EMAILJS_USER_ID: ${{ secrets.EMAILJS_USER_ID || 'placeholder' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci || npm ci
      - name: Validate Environment Variables
        run: |
          missing=false
          if [ "${EMAILJS_SERVICE_ID}" = "placeholder" ]; then
            echo "::warning::EMAILJS_SERVICE_ID secret is not configured."
            missing=true
          fi
          if [ "${EMAILJS_TEMPLATE_ID}" = "placeholder" ]; then
            echo "::warning::EMAILJS_TEMPLATE_ID secret is not configured."
            missing=true
          fi
          if [ "${EMAILJS_USER_ID}" = "placeholder" ]; then
            echo "::warning::EMAILJS_USER_ID secret is not configured."
            missing=true
          fi
          if [ "$missing" = true ]; then
            echo "::error::EmailJS secrets are required. Add EMAILJS_SERVICE_ID, EMAILJS_TEMPLATE_ID, and EMAILJS_USER_ID in repository secrets. See README.md section 'EmailJS 시크릿 설정'."
            exit 1
          fi
      - run: npm run lint
      - run: npm test
      - run: npm run build
