name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EMAILJS_SERVICE_ID: ${{ secrets.EMAILJS_SERVICE_ID }}
      EMAILJS_TEMPLATE_ID: ${{ secrets.EMAILJS_TEMPLATE_ID }}
      EMAILJS_USER_ID: ${{ secrets.EMAILJS_USER_ID }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: echo "Checking environment variables"
      - run: echo $EMAILJS_SERVICE_ID && echo $EMAILJS_TEMPLATE_ID && echo $EMAILJS_USER_ID
      - run: npm run lint
      - run: npm test
      - run: npm run build
