name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    env:
      EMAILJS_SERVICE_ID: ${{ secrets.EMAILJS_SERVICE_ID }}
      EMAILJS_TEMPLATE_ID: ${{ secrets.EMAILJS_TEMPLATE_ID }}
      EMAILJS_USER_ID: ${{ secrets.EMAILJS_USER_ID }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci --prefer-offline --no-audit --progress=false
      - run: npm run check:secrets

  build:
    needs: check-secrets
    runs-on: ubuntu-latest
    env:
      # EmailJS credentials should be configured as GitHub Secrets.
      EMAILJS_SERVICE_ID: ${{ secrets.EMAILJS_SERVICE_ID }}
      EMAILJS_TEMPLATE_ID: ${{ secrets.EMAILJS_TEMPLATE_ID }}
      EMAILJS_USER_ID: ${{ secrets.EMAILJS_USER_ID }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci || npm ci
      - run: npm run lint
      - run: npm test
      - run: npm run build
